# Project: ÏîÄ¿2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
RES      = lastShooter_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"D:/program/DEV_CPP/Dev-Cpp/MinGW64/lib" -L"D:/program/DEV_CPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -lwinmm -leasyx -lgdi32 -lole32 -g3
INCS     = -I"D:/program/DEV_CPP/Dev-Cpp/MinGW64/include" -I"D:/program/DEV_CPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/program/DEV_CPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/program/DEV_CPP/Dev-Cpp/MinGW64/include" -I"D:/program/DEV_CPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/program/DEV_CPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/program/DEV_CPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = lastShooter.exe
CXXFLAGS = $(CXXINCS) -g3 -lwsock32
CFLAGS   = $(INCS) -g3 -lwsock32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

lastShooter_private.res: lastShooter_private.rc 
	$(WINDRES) -i lastShooter_private.rc --input-format=rc -o lastShooter_private.res -O coff 

